# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-02 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
