# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-04 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20160904_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='cost',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='text',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
