# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-04 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_auto_20160902_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
