# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-04 17:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_auto_20160904_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
